# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestWithQuickSample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestWithQuickSample

  target 'TestWithQuickSampleTests' do
    inherit! :search_paths
    # Pods for testing
	use_frameworks!
	pod 'Quick'
	pod 'Nimble'
  end

  target 'TestWithQuickSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
